name: stepfront_utilities
description: Stepfront utilities for snackbars, updating locale, custom exception model.
version: 0.0.1
repository: https://github.com/21kkfy/stepfront-utilities

environment:
  sdk: ">=2.19.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  get: ^4.6.5
  image: ^4.0.15
