name: zerotech_utilities
description: ZeroTech utilities for snackbars, updating locale, custom exception model.
version: 0.2.0
repository: https://github.com/21kkfy/ZeroTech-utilities

environment:
  sdk: ">=2.19.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  encrypt: ^5.0.1
  flutter_dotenv: ^5.0.2
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.8.0
  flutter_svg: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.6
  image: ^4.0.17
  intl: ^0.18.1
  path_provider: ^2.0.15
